services:
  app:
    build: .
    ports:
      - "9000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/${DB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - spring-net

  db:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - spring-net
    ports:
      - "3307:3306"

networks:
  spring-net:
    driver: bridge

volumes:
  db_data:
